/** C++ Ranges (Part 6 of n) — std::views::cartesian_product, views::take
 *  Modern C++ Series — Ep. 231
 */

#include <iostream>
#include <ranges>
#include <string>
#include <vector>
#include <print>

/*
    We are goint to be looking at the range view std::views::cartesian_product.


- ranges::cartesian_product_view / views::cartesian_product: (C++23)
  
    A view consisting of tuples generated by taking the n-ary Cartesian product 
of the adapted views.


Call signature:

    template< ranges::viewable_range... Rs >
        requires [see below]
    constexpr ranges::view auto cartesian_product(Rs&&... rs);
    ~~~~~~~~                                          ^^^
    This means that it                 This means you can pass any number
 could be resolved at                of viewable_range parameters. 
 compile-time.


NOTE:
    This is a variadic template because it takes a 'parameter pack' (the '...' syntax).

    Example:

        template<typename T, typename... Args>
        std::shared_ptr<T> make_shared(Args&&... params);
                                             ~~~~~~~~~~~
                                         These arguments are forwarded to T’s constructor.

`cartesian_product_view` is a range adaptor that takes N views (where N > 0) and 
produces a view of tuples representing the N-ary Cartesian product of the 
provided ranges.

*/

int main()
{
    // Random units in a game generator
    std::vector<std::string> names{"Mike", "Merlin", "Arthur"};
    std::vector<int>         health{10,20,30,40};
    std::vector<int>         magic{11,21,31,41};

    // The goal is to pre-populate a structure using std::views::cartesian_product
    // by combining the names, health, and magic values into all possible triplets.

    auto random_units = std::views::cartesian_product(names, health, magic) 
                        | std::ranges::to<std::vector>();
    for(const auto& unit: random_units)
    {
        std::println( "{}", unit);
    }
    // The output shows all combinations of (name, health, magic) generated 
    // by the Cartesian product of the three input ranges.

/*
("Mike", 10, 11)
("Mike", 10, 21)
("Mike", 10, 31)
("Mike", 10, 41)
("Mike", 20, 11)
("Mike", 20, 21)
("Mike", 20, 31)
("Mike", 20, 41)
("Mike", 30, 11)
("Mike", 30, 21)
("Mike", 30, 31)
("Mike", 30, 41)
("Mike", 40, 11)
("Mike", 40, 21)
("Mike", 40, 31)
("Mike", 40, 41)
("Merlin", 10, 11)
("Merlin", 10, 21)
("Merlin", 10, 31)
("Merlin", 10, 41)
("Merlin", 20, 11)
("Merlin", 20, 21)
("Merlin", 20, 31)
("Merlin", 20, 41)
("Merlin", 30, 11)
("Merlin", 30, 21)
("Merlin", 30, 31)
("Merlin", 30, 41)
("Merlin", 40, 11)
("Merlin", 40, 21)
("Merlin", 40, 31)
("Merlin", 40, 41)
("Arthur", 10, 11)
("Arthur", 10, 21)
("Arthur", 10, 31)
("Arthur", 10, 41)
("Arthur", 20, 11)
("Arthur", 20, 21)
("Arthur", 20, 31)
("Arthur", 20, 41)
("Arthur", 30, 11)
("Arthur", 30, 21)
("Arthur", 30, 31)
("Arthur", 30, 41)
("Arthur", 40, 11)
("Arthur", 40, 21)
("Arthur", 40, 31)
("Arthur", 40, 41)
*/

    return 0;
}